import { upgradedEventJson } from "./upgrade-v1.js";

export interface StoreMigration {
  readonly rewriteEventBody: ((body: string) => string | null) | null;
  readonly statements: readonly string[];
  readonly version: number;
}

export const STORE_MIGRATIONS: readonly StoreMigration[] = [
  {
    rewriteEventBody: null,
    statements: [
      "CREATE TABLE store_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)",
      "CREATE TABLE events (seq INTEGER PRIMARY KEY AUTOINCREMENT, event_id TEXT NOT NULL UNIQUE, adapter_id TEXT NOT NULL, kind TEXT NOT NULL, origin TEXT NOT NULL, flight_id TEXT, repo_common_dir TEXT, branch TEXT, occurred_at TEXT, observed_at TEXT NOT NULL, body TEXT NOT NULL)",
      "CREATE INDEX events_flight ON events (flight_id)",
      "CREATE INDEX events_branch ON events (repo_common_dir, branch)",
      "CREATE INDEX events_time ON events (occurred_at, observed_at)",
      "CREATE TABLE coverage (seq INTEGER PRIMARY KEY AUTOINCREMENT, adapter_id TEXT NOT NULL, flight_ids TEXT NOT NULL, repos TEXT NOT NULL, branches TEXT NOT NULL, body TEXT NOT NULL)",
      "CREATE INDEX coverage_adapter ON coverage (adapter_id)",
      "CREATE TABLE snapshots (seq INTEGER PRIMARY KEY AUTOINCREMENT, snapshot_id TEXT NOT NULL UNIQUE, selector_key TEXT NOT NULL, contract_digest TEXT NOT NULL, event_count INTEGER NOT NULL, manifest TEXT NOT NULL, coverage TEXT NOT NULL)",
      "CREATE INDEX snapshots_selector ON snapshots (selector_key)",
      "CREATE TABLE snapshot_events (snapshot_id TEXT NOT NULL, ordinal INTEGER NOT NULL, event_id TEXT NOT NULL, PRIMARY KEY (snapshot_id, ordinal))",
    ],
    version: 1,
  },
  {
    rewriteEventBody: upgradedEventJson,
    statements: [],
    version: 2,
  },
  {
    rewriteEventBody: null,
    statements: [
      "CREATE TABLE IF NOT EXISTS usage_facts (fact_id TEXT PRIMARY KEY, harness TEXT, repo TEXT NOT NULL, branch TEXT, occurred_ms INTEGER, scope TEXT NOT NULL, body TEXT NOT NULL)",
      "CREATE INDEX IF NOT EXISTS usage_facts_time ON usage_facts (occurred_ms)",
      "CREATE TABLE IF NOT EXISTS usage_disagreements (fact_id TEXT NOT NULL, harness TEXT, field TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY (fact_id, field))",
      "CREATE INDEX IF NOT EXISTS usage_disagreements_harness ON usage_disagreements (harness)",
      "CREATE TABLE IF NOT EXISTS usage_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS harness_cursors (ref_key TEXT PRIMARY KEY, harness TEXT NOT NULL, path TEXT NOT NULL, mtime_ms REAL, size INTEGER, cursor TEXT, last_event_id TEXT, updated_at TEXT NOT NULL)",
    ],
    version: 3,
  },
  {
    rewriteEventBody: null,
    statements: [
      "CREATE INDEX IF NOT EXISTS events_kind ON events (kind)",
      "DROP TABLE IF EXISTS usage_facts",
      "DROP TABLE IF EXISTS usage_disagreements",
      "DROP TABLE IF EXISTS usage_members",
      "DROP TABLE IF EXISTS usage_links",
      "DROP TABLE IF EXISTS usage_worktrees",
      "DROP TABLE IF EXISTS usage_unresolved",
      "DROP TABLE IF EXISTS usage_dirty",
      "DELETE FROM usage_meta",
      "CREATE TABLE usage_facts (fact_id TEXT PRIMARY KEY, component INTEGER NOT NULL, harness TEXT, repo TEXT NOT NULL, branch TEXT, scope TEXT NOT NULL, session_key TEXT, figure INTEGER NOT NULL, occurred_ms INTEGER, body TEXT NOT NULL)",
      "CREATE INDEX usage_facts_time ON usage_facts (occurred_ms)",
      "CREATE INDEX usage_facts_component ON usage_facts (component)",
      "CREATE INDEX usage_facts_session ON usage_facts (session_key, figure)",
      "CREATE TABLE usage_disagreements (fact_id TEXT NOT NULL, component INTEGER NOT NULL, harness TEXT, field TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY (fact_id, field))",
      "CREATE INDEX usage_disagreements_component ON usage_disagreements (component)",
      "CREATE TABLE usage_members (seq INTEGER PRIMARY KEY, component INTEGER NOT NULL)",
      "CREATE INDEX usage_members_component ON usage_members (component)",
      "CREATE TABLE usage_links (link TEXT PRIMARY KEY, component INTEGER NOT NULL)",
      "CREATE INDEX usage_links_component ON usage_links (component)",
      "CREATE TABLE usage_worktrees (worktree TEXT NOT NULL, component INTEGER NOT NULL, PRIMARY KEY (worktree, component))",
      "CREATE INDEX usage_worktrees_component ON usage_worktrees (component)",
      "CREATE TABLE usage_unresolved (event_id TEXT PRIMARY KEY, component INTEGER NOT NULL)",
      "CREATE INDEX usage_unresolved_component ON usage_unresolved (component)",
      "CREATE TABLE usage_dirty (component INTEGER PRIMARY KEY)",
    ],
    version: 4,
  },
  {
    rewriteEventBody: null,
    statements: [
      "INSERT OR IGNORE INTO store_meta(key,value) VALUES ('agent_store_id','store_' || lower(hex(randomblob(16))))",
      "INSERT OR IGNORE INTO store_meta(key,value) VALUES ('agent_generation','1')",
      "INSERT OR IGNORE INTO store_meta(key,value) VALUES ('agent_revision','0')",
      "INSERT OR IGNORE INTO store_meta(key,value) VALUES ('agent_epoch',lower(hex(randomblob(16))))",
      "CREATE TRIGGER agent_events_insert AFTER INSERT ON events BEGIN UPDATE store_meta SET value = CAST(value AS INTEGER) + 1 WHERE key = 'agent_revision'; END",
      "CREATE TRIGGER agent_events_delete AFTER DELETE ON events BEGIN UPDATE store_meta SET value = CAST(value AS INTEGER) + 1 WHERE key = 'agent_revision'; END",
      "CREATE TRIGGER agent_coverage_insert AFTER INSERT ON coverage BEGIN UPDATE store_meta SET value = CAST(value AS INTEGER) + 1 WHERE key = 'agent_revision'; END",
      "CREATE TRIGGER agent_coverage_delete AFTER DELETE ON coverage BEGIN UPDATE store_meta SET value = CAST(value AS INTEGER) + 1 WHERE key = 'agent_revision'; END",
      "CREATE INDEX events_agent_scope_seq ON events(repo_common_dir,branch,seq)",
      "CREATE INDEX events_agent_time ON events(COALESCE(occurred_at,observed_at),seq)",
      "CREATE INDEX events_agent_evidence_ref ON events(json_extract(body,'$.evidence.ref'))",
      "CREATE INDEX events_agent_worktree ON events(json_extract(body,'$.context.worktreePath'),seq)",
      "CREATE INDEX events_agent_harness ON events(json_extract(body,'$.ai.harness'),seq)",
      "CREATE INDEX events_agent_source ON events(adapter_id,seq)",
      "CREATE TABLE agent_bases(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,store_id TEXT NOT NULL,generation INTEGER NOT NULL,query_key TEXT NOT NULL,repo_id TEXT,scope_key TEXT NOT NULL,created_at TEXT NOT NULL,body TEXT NOT NULL,content_available INTEGER NOT NULL DEFAULT 1,content_digest TEXT NOT NULL)",
      "CREATE INDEX agent_bases_scope ON agent_bases(store_id,generation,repo_id,query_key,seq)",
      "CREATE INDEX agent_bases_query ON agent_bases(store_id,generation,query_key,seq)",
      "CREATE INDEX agent_bases_orientation ON agent_bases(store_id,generation,scope_key,created_at,id)",
      "CREATE TABLE agent_basis_headers(id TEXT PRIMARY KEY,body TEXT NOT NULL)",
      "CREATE TABLE agent_basis_events(basis_id TEXT NOT NULL,event_id TEXT NOT NULL,PRIMARY KEY(basis_id,event_id))",
      "CREATE TABLE agent_results(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,store_id TEXT NOT NULL,generation INTEGER NOT NULL,basis_id TEXT NOT NULL,capability TEXT NOT NULL,query_digest TEXT NOT NULL,projection_version TEXT NOT NULL,result_digest TEXT NOT NULL,body TEXT NOT NULL,projection TEXT,byte_count INTEGER NOT NULL,content_digest TEXT NOT NULL)",
      "CREATE INDEX agent_results_lookup ON agent_results(store_id,generation,basis_id,capability,query_digest,seq)",
      "CREATE INDEX agent_results_retained ON agent_results(seq) WHERE projection IS NOT NULL",
      "CREATE TABLE agent_result_headers(id TEXT PRIMARY KEY,body TEXT NOT NULL,summary TEXT NOT NULL,disclosures TEXT NOT NULL,resolutions TEXT NOT NULL DEFAULT '[]',item_count INTEGER NOT NULL,series_count INTEGER NOT NULL)",
      "CREATE TABLE agent_result_items(result_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('item','series')),position INTEGER NOT NULL,body TEXT NOT NULL,byte_count INTEGER NOT NULL,PRIMARY KEY(result_id,kind,position))",
      "CREATE TABLE agent_cursors(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,generation INTEGER NOT NULL,epoch TEXT NOT NULL,body TEXT NOT NULL)",
      "CREATE TABLE agent_event_reads(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,generation INTEGER NOT NULL,epoch TEXT NOT NULL,selector_key TEXT NOT NULL,selector_body TEXT NOT NULL,scope_body TEXT,filters_body TEXT NOT NULL,upper_seq INTEGER NOT NULL,coverage TEXT NOT NULL,created_at TEXT NOT NULL)",
      "CREATE TABLE agent_coverage_latest(adapter_id TEXT NOT NULL,flight_id TEXT NOT NULL,repo_id TEXT NOT NULL,branch TEXT NOT NULL,seq INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(adapter_id,flight_id,repo_id,branch))",
      "CREATE INDEX agent_coverage_scope ON agent_coverage_latest(repo_id,branch,flight_id,adapter_id)",
      "INSERT OR REPLACE INTO agent_coverage_latest SELECT c.adapter_id,COALESCE(f.value,''),COALESCE(r.value,''),COALESCE(b.value,''),c.seq,c.body FROM coverage c LEFT JOIN json_each(c.flight_ids) f LEFT JOIN json_each(c.repos) r LEFT JOIN json_each(c.branches) b ORDER BY c.seq",
      "CREATE TABLE agent_operation_plans(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,generation INTEGER NOT NULL,plan_digest TEXT NOT NULL,validity TEXT NOT NULL,body TEXT NOT NULL)",
      "CREATE TABLE agent_operations(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,generation INTEGER NOT NULL,revision INTEGER NOT NULL,state TEXT NOT NULL,body TEXT NOT NULL)",
      "CREATE INDEX agent_operations_recovery ON agent_operations(store_id,generation,state,id)",
      "CREATE TABLE agent_reservations(store_id TEXT NOT NULL,generation INTEGER NOT NULL,key TEXT NOT NULL,plan_id TEXT NOT NULL,plan_digest TEXT NOT NULL,operation_id TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(store_id,generation,key))",
      "CREATE TABLE agent_operation_steps(seq INTEGER PRIMARY KEY AUTOINCREMENT,operation_id TEXT NOT NULL,revision INTEGER NOT NULL,body TEXT NOT NULL)",
      "CREATE INDEX agent_operation_steps_recovery ON agent_operation_steps(operation_id,revision,seq)",
      "CREATE TABLE agent_operation_aliases(store_id TEXT NOT NULL,generation INTEGER NOT NULL,operation_id TEXT NOT NULL,target_store_id TEXT NOT NULL,target_generation INTEGER NOT NULL,PRIMARY KEY(store_id,generation,operation_id))",
      "CREATE TABLE agent_learning(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,store_id TEXT NOT NULL,generation INTEGER NOT NULL,revision INTEGER NOT NULL,kind TEXT NOT NULL,repo_id TEXT,worktree_id TEXT,flight_id TEXT,wider_scope INTEGER NOT NULL,status TEXT,search_text TEXT NOT NULL,updated_at TEXT NOT NULL,body TEXT NOT NULL)",
      "CREATE INDEX agent_learning_scope ON agent_learning(store_id,generation,repo_id,kind,status,seq)",
      "CREATE INDEX agent_learning_worktree ON agent_learning(store_id,generation,worktree_id,seq)",
      "CREATE INDEX agent_learning_flight ON agent_learning(store_id,generation,flight_id,seq)",
      "CREATE TABLE agent_learning_history(id TEXT NOT NULL,revision INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(id,revision))",
      "CREATE TABLE agent_learning_mutations(store_id TEXT NOT NULL,generation INTEGER NOT NULL,key TEXT NOT NULL,action TEXT NOT NULL,digest TEXT NOT NULL,body TEXT NOT NULL,PRIMARY KEY(store_id,generation,key))",
      "CREATE TABLE agent_evaluations(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,store_id TEXT NOT NULL,generation INTEGER NOT NULL,target_kind TEXT NOT NULL,target_id TEXT NOT NULL,target_revision INTEGER NOT NULL,created_at TEXT NOT NULL,body TEXT NOT NULL)",
      "CREATE INDEX agent_evaluations_target ON agent_evaluations(store_id,generation,target_id,seq)",
    ],
    version: 5,
  },
  {
    rewriteEventBody: null,
    statements: [
      "CREATE TABLE agent_source_associations(event_seq INTEGER PRIMARY KEY,adapter_id TEXT NOT NULL,repo_id TEXT NOT NULL,branch TEXT NOT NULL,flight_id TEXT NOT NULL,worktree_id TEXT NOT NULL,tool TEXT NOT NULL)",
      "CREATE INDEX agent_source_associations_scope ON agent_source_associations(repo_id,worktree_id,tool,adapter_id,branch,flight_id)",
      "CREATE INDEX agent_source_associations_adapter ON agent_source_associations(adapter_id,repo_id,branch,flight_id,worktree_id,tool)",
      "INSERT INTO agent_source_associations SELECT seq,adapter_id,COALESCE(repo_common_dir,''),COALESCE(branch,''),COALESCE(flight_id,''),COALESCE(json_extract(body,'$.context.worktreePath'),''),COALESCE(json_extract(body,'$.ai.harness'),'') FROM events",
      "CREATE TRIGGER agent_source_associations_insert AFTER INSERT ON events BEGIN INSERT INTO agent_source_associations VALUES (NEW.seq,NEW.adapter_id,COALESCE(NEW.repo_common_dir,''),COALESCE(NEW.branch,''),COALESCE(NEW.flight_id,''),COALESCE(json_extract(NEW.body,'$.context.worktreePath'),''),COALESCE(json_extract(NEW.body,'$.ai.harness'),'')); END",
      "CREATE TRIGGER agent_source_associations_delete AFTER DELETE ON events BEGIN DELETE FROM agent_source_associations WHERE event_seq = OLD.seq; END",
      "CREATE TABLE agent_writer_owners(id TEXT PRIMARY KEY,pid INTEGER NOT NULL,process_start TEXT,closed INTEGER NOT NULL DEFAULT 0)",
      "ALTER TABLE agent_operations ADD COLUMN owner_id TEXT",
      "CREATE INDEX agent_operations_owner ON agent_operations(state,owner_id,id)",
    ],
    version: 6,
  },
  {
    rewriteEventBody: null,
    statements: [
      "CREATE INDEX events_agent_replacement ON events(adapter_id,occurred_at,seq)",
      "CREATE INDEX agent_basis_events_source ON agent_basis_events(event_id,basis_id)",
      "CREATE INDEX snapshot_events_source ON snapshot_events(event_id,snapshot_id)",
      "CREATE INDEX agent_results_basis ON agent_results(basis_id,id)",
    ],
    version: 7,
  },
  {
    rewriteEventBody: null,
    statements: [
      "CREATE INDEX agent_operation_aliases_operation ON agent_operation_aliases(operation_id)",
    ],
    version: 8,
  },
];

export const STORE_SCHEMA_VERSION = STORE_MIGRATIONS.length;
